# Generated by Django 4.0.4 on 2023-01-13 08:28

import backend.product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('description', models.TextField(verbose_name='describe_product')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to=backend.product.models.product_image_location)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
